import { capabilities, registry } from "@/capabilities/registry";
import type { Caller, CapabilityExecution } from "@/capabilities/types";
import { parseCommand } from "./parser";

type Execute = (id: string, params?: Record<string, unknown>, caller?: Caller) => Promise<CapabilityExecution>;
const json = (value: unknown) => JSON.stringify(value, null, 2);
const definition = (id: string) => { const item = registry.get(id); if (!item) return null; return { id: item.id, title: item.title, description: item.description, params: item.params, examples: item.examples, cli: item.cli, keyboard: item.keyboard, accessibility: item.accessibility, risk: item.risk, requiresConfirmation: item.requiresConfirmation ?? false }; };
export const helpText = `MICHAELOS AGENT CLI\n\nDiscovery: help → capabilities → describe <id> → run <id> <parameters>\n\nhelp                                      Show this guide\ncapabilities [--search text] [--category namespace] [--json]\ndescribe <capability-id> [--json]\nrun <capability-id> [--name value] [--json '{"name":"value"}']\nhistory [--caller caller] [--capability id] [--json]\nclear                                     Clear CLI output only\n\nAction Key invocation: enter the six-chord Agent Gateway Keys, then an Action Key such as\nPROJECT VIEW atlas-platform ENTER`;

export async function runCommand(line: string, options: { caller: Caller; execute: Execute; history: CapabilityExecution[]; clear: () => void }) {
  const parsed = parseCommand(line.trim()); const { command, positional, flags } = parsed;
  if (!command) return "";
  if (command === "help") return helpText;
  if (command === "clear") { options.clear(); return ""; }
  if (command === "capabilities") { let rows = capabilities; if (flags.search) { const term = String(flags.search).toLowerCase(); rows = rows.filter(item => `${item.id} ${item.title} ${item.description}`.toLowerCase().includes(term)); } if (flags.category) rows = rows.filter(item => item.id.startsWith(`${String(flags.category)}.`)); const data = rows.map(item => ({ id: item.id, description: item.description, risk: item.risk, requiresParameters: item.params.some(param => param.required) })); return flags.json ? json(data) : data.map(item => `${item.id.padEnd(36)} ${item.risk.padEnd(11)} ${item.requiresParameters ? "params" : "—"}  ${item.description}`).join("\n"); }
  if (command === "describe") { const item = definition(positional[0]); if (!item) return json({ ok: false, error: { code: "CAPABILITY_NOT_FOUND", message: `Capability "${positional[0]}" is not registered.`, suggestion: "Run capabilities to discover valid IDs." } }); return flags.json ? json(item) : `${item.id}\n${item.description}\n\nParameters\n${item.params.length ? item.params.map(p => `  ${p.name}: ${p.type}${p.required ? " (required)" : ""} — ${p.description}`).join("\n") : "  none"}\n\nCLI\n  ${item.cli.command}\n\nAction Keys\n  ${item.keyboard.template.join(" ")}\n\nAccessibility\n  ${item.accessibility.label}\n\nRisk\n  ${item.risk}\n\nExample\n  ${json(item.examples[0]?.params ?? {})}`; }
  if (command === "history") { let rows = options.history; if (flags.caller) rows = rows.filter(item => item.caller === flags.caller); if (flags.capability) rows = rows.filter(item => item.capabilityId === flags.capability); return flags.json ? json(rows) : rows.map(item => `${item.timestamp}  ${item.status === "success" ? "✓" : "✗"}  ${item.caller.padEnd(13)} ${item.capabilityId}  ${item.durationMs} ms`).join("\n") || "No matching executions."; }
  if (command === "run") { const id = positional[0]; const params: Record<string, unknown> = { ...flags }; if (typeof flags.json === "string") { delete params.json; try { Object.assign(params, JSON.parse(flags.json)); } catch { return json({ ok: false, error: { code: "INVALID_JSON", message: "The --json value is not valid JSON.", suggestion: `Run describe ${id} to inspect its parameters.` } }); } } else delete params.json; const event = await options.execute(id, params, options.caller); return json({ ok: event.status === "success", executionId: event.executionId, capability: event.capabilityId, caller: event.caller, durationMs: event.durationMs, data: event.result, error: event.error }); }
  return json({ ok: false, error: { code: "COMMAND_NOT_FOUND", message: `Command "${command}" is not available.`, suggestion: "Run help to see available commands." } });
}
