import { articles, experience, projects, skills } from "@/data/content";
import { Capability, CapabilityError } from "./types";

const required = (params: Record<string, unknown>, key: string) => {
  const value = params[key];
  if (value === undefined || value === "") throw new CapabilityError("MISSING_PARAMETER", `The parameter “${key}” is required.`, value, `Provide --${key} <value>.`);
  return String(value);
};
const search = <T>(items: T[], fields: (item: T) => string[], query: string) => items.filter(item => fields(item).some(value => value.toLowerCase().includes(query.toLowerCase())));
const cap = (definition: Capability) => definition;
const nav = (id: string, title: string, path: string, token: string) => cap({ id, title, description: `Navigate to the ${title.toLowerCase()} page.`, hotkey: `CTRL+ALT+SPACE NAVIGATION ${token} ENTER`, params: [], examples: [{ description: `Open ${title}.`, params: {}, cli: `run ${id}` }], accessibility: { label: `Open ${title}` }, risk: "read", async execute(_, ctx) { ctx.navigate(path); return { path }; } });

export const capabilities: Capability[] = [
  nav("navigation.goHome", "Home", "/", "HOME"), nav("navigation.goProjects", "Projects", "/projects", "PROJECTS"), nav("navigation.goExperience", "Experience", "/experience", "EXPERIENCE"), nav("navigation.goBlog", "Writing", "/blog", "BLOG"), nav("navigation.goCv", "CV", "/cv", "CV"), nav("navigation.goCapabilities", "Capabilities", "/capabilities", "CAPABILITIES"),
  cap({ id: "project.list", title: "List projects", description: "Return all portfolio projects, optionally limited to featured work.", hotkey: "CTRL+ALT+SPACE PROJECT LIST ENTER", params: [{ name: "featured", description: "Only return featured projects.", type: "boolean", required: false }], examples: [{ description: "List every project.", params: {}, cli: "run project.list" }], accessibility: { label: "List portfolio projects" }, risk: "read", async execute(p) { return { projects: p.featured ? projects.filter(x => x.featured) : projects, count: p.featured ? projects.filter(x => x.featured).length : projects.length }; } }),
  cap({ id: "project.search", title: "Search projects", description: "Search project names, summaries and technologies using natural terms.", hotkey: "CTRL+ALT+SPACE PROJECT SEARCH <query> ENTER", aliases: ["find project"], params: [{ name: "query", description: "Words to search for.", type: "string", required: true }], examples: [{ description: "Find platform work.", params: { query: "platform engineering" }, cli: "run project.search --query \"platform engineering\"" }], accessibility: { label: "Search portfolio projects" }, risk: "read", async execute(p) { const q = required(p, "query"); const matches = search(projects, x => [x.name, x.summary, x.description, x.technologies.join(" ")], q); return { projects: matches, count: matches.length, query: q }; } }),
  cap({ id: "project.view", title: "View project", description: "Open the detail page for a project using its unique slug.", hotkey: "CTRL+ALT+SPACE PROJECT VIEW <slug> ENTER", aliases: ["open project", "show project", "inspect project"], params: [{ name: "slug", description: "The unique project slug.", type: "string", required: true }], examples: [{ description: "Open the Atlas project.", params: { slug: "atlas-platform" }, cli: "run project.view --slug atlas-platform" }], accessibility: { label: "Open project details" }, risk: "read", async execute(p, ctx) { const slug = required(p, "slug"); const project = projects.find(x => x.slug === slug); if (!project) throw new CapabilityError("PROJECT_NOT_FOUND", `No project exists with the slug “${slug}”.`, slug, `Try one of: ${projects.map(x => x.slug).join(", ")}.`); const path = `/projects?project=${slug}`; ctx.navigate(path); return { project, path }; } }),
  cap({ id: "project.filter", title: "Filter projects", description: "Filter projects by technology or status.", hotkey: "CTRL+ALT+SPACE PROJECT FILTER <value> ENTER", params: [{ name: "value", description: "Technology or status.", type: "string", required: true }], examples: [{ description: "Show TypeScript projects.", params: { value: "TypeScript" }, cli: "run project.filter --value TypeScript" }], accessibility: { label: "Filter portfolio projects" }, risk: "read", async execute(p) { const value = required(p, "value"); return { projects: search(projects, x => [x.status, ...x.technologies], value), filter: value }; } }),
  cap({ id: "experience.list", title: "List experience", description: "Return professional roles in reverse chronological order.", hotkey: "CTRL+ALT+SPACE EXPERIENCE LIST ENTER", params: [], examples: [{ description: "List work history.", params: {}, cli: "run experience.list" }], accessibility: { label: "List professional experience" }, risk: "read", async execute() { return { experience }; } }),
  cap({ id: "article.list", title: "List articles", description: "Return all published writing.", hotkey: "CTRL+ALT+SPACE ARTICLE LIST ENTER", params: [], examples: [{ description: "List articles.", params: {}, cli: "run article.list" }], accessibility: { label: "List published articles" }, risk: "read", async execute() { return { articles: articles.filter(x => x.status === "published") }; } }),
  cap({ id: "article.search", title: "Search articles", description: "Search article titles, summaries and tags.", hotkey: "CTRL+ALT+SPACE ARTICLE SEARCH <query> ENTER", params: [{ name: "query", description: "Words to search for.", type: "string", required: true }], examples: [{ description: "Find local-first writing.", params: { query: "local-first" }, cli: "run article.search --query local-first" }], accessibility: { label: "Search published articles" }, risk: "read", async execute(p) { const q = required(p, "query"); return { articles: search(articles, x => [x.title, x.summary, x.tags.join(" ")], q), query: q }; } }),
  cap({ id: "article.view", title: "View article", description: "Open an article by slug.", hotkey: "CTRL+ALT+SPACE ARTICLE VIEW <slug> ENTER", params: [{ name: "slug", description: "Unique article slug.", type: "string", required: true }], examples: [{ description: "Open capabilities essay.", params: { slug: "capabilities-not-interfaces" }, cli: "run article.view --slug capabilities-not-interfaces" }], accessibility: { label: "Open article" }, risk: "read", async execute(p, ctx) { const slug = required(p, "slug"); const article = articles.find(x => x.slug === slug); if (!article) throw new CapabilityError("ARTICLE_NOT_FOUND", `No article exists with slug “${slug}”.`, slug); ctx.navigate(`/blog?article=${slug}`); return { article, path: `/blog?article=${slug}` }; } }),
  cap({ id: "skill.list", title: "List skills", description: "Return skills and their categories.", hotkey: "CTRL+ALT+SPACE SKILL LIST ENTER", params: [], examples: [{ description: "List skills.", params: {}, cli: "run skill.list" }], accessibility: { label: "List skills" }, risk: "read", async execute() { return { skills }; } }),
  cap({ id: "cv.view", title: "View CV", description: "Open the curriculum vitae.", hotkey: "CTRL+ALT+SPACE CV VIEW ENTER", params: [], examples: [{ description: "Open CV.", params: {}, cli: "run cv.view" }], accessibility: { label: "View curriculum vitae" }, risk: "read", async execute(_, ctx) { ctx.navigate("/cv"); return { path: "/cv" }; } }),
  cap({ id: "cv.exportJson", title: "Export CV as JSON", description: "Download the complete CV as structured JSON.", hotkey: "CTRL+ALT+SPACE CV EXPORT JSON ENTER", params: [], examples: [{ description: "Export CV.", params: {}, cli: "run cv.exportJson" }], accessibility: { label: "Export CV as JSON" }, risk: "read", async execute() { return { profile: { name: "Mike Ajijola", role: "Platform engineer & systems thinker" }, experience, projects, skills }; } }),
  cap({ id: "cv.print", title: "Print CV", description: "Open the browser print dialog for the CV.", hotkey: "CTRL+ALT+SPACE CV PRINT ENTER", params: [], examples: [{ description: "Print CV.", params: {}, cli: "run cv.print" }], accessibility: { label: "Print curriculum vitae" }, risk: "read", async execute() { if (typeof window !== "undefined") window.print(); return { opened: true }; } }),
  cap({ id: "system.getApplicationInfo", title: "Get application info", description: "Describe the browser runtime and capability architecture.", hotkey: "CTRL+ALT+SPACE SYSTEM INFO ENTER", params: [], examples: [{ description: "Inspect runtime.", params: {}, cli: "run system.getApplicationInfo" }], accessibility: { label: "Get application information" }, risk: "read", async execute() { return { runtime: "browser", architecture: "capability-first", persistence: "SQLite WASM + OPFS", backend: false, version: "1.0.0" }; } }),
  cap({ id: "system.reset", title: "Reset local application", description: "Clear local history and restore seeded application data.", hotkey: "CTRL+ALT+SPACE SYSTEM RESET CONFIRM ENTER", params: [{ name: "confirm", description: "Confirm destructive reset.", type: "boolean", required: true }], examples: [{ description: "Reset local state.", params: { confirm: true }, cli: "run system.reset --confirm true" }], accessibility: { label: "Reset all local application data" }, risk: "destructive", requiresConfirmation: true, async execute(p) { if (p.confirm !== true && p.confirm !== "true") throw new CapabilityError("CONFIRMATION_REQUIRED", "Reset requires explicit confirmation.", p.confirm, "Pass --confirm true."); localStorage.clear(); return { reset: true }; } }),
];

export const registry = new Map(capabilities.map(c => [c.id, c]));
