"use client";
import { useEffect, useRef, useState } from "react";
import { useCapabilities } from "@/capabilities/context";
import { CapabilityInfo } from "@/components/common/CapabilityInfo";
import { runCommand } from "@/terminal/commands";
import type { SurfaceTab } from "@/capabilities/types";

function SurfaceAction({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { const { execute } = useCapabilities(); return <span className="surface-action"><button data-capability-id={id} aria-label={label} onClick={() => execute(id)}>{children}</button><CapabilityInfo capabilityId={id} controlLabel={label}/></span>; }

function TerminalClient() {
  const runtime = useCapabilities(); const runtimeRef = useRef(runtime); runtimeRef.current = runtime; const host = useRef<HTMLDivElement>(null); const terminal = useRef<import("@xterm/xterm").Terminal | null>(null); const line = useRef("");
  useEffect(() => { let disposed = false; void Promise.all([import("@xterm/xterm"), import("@xterm/addon-fit")]).then(([xterm, fitModule]) => { if (disposed || !host.current) return; const instance = new xterm.Terminal({ cursorBlink: true, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12, theme: { background: "#15201b", foreground: "#dfe8e2", cursor: "#d4f05d", green: "#d4f05d" }, convertEol: true, scrollback: 1000 }); const fit = new fitModule.FitAddon(); instance.loadAddon(fit); instance.open(host.current); fit.fit(); terminal.current = instance; instance.onData(data => { if (data === "\r") { const command = line.current; line.current = ""; const active = runtimeRef.current; active.appendTranscript(`› ${command}`); void runCommand(command, { caller: "terminal", execute: active.execute, history: active.history, clear: active.clearTranscript }).then(output => { if (output) runtimeRef.current.appendTranscript(output); }); } else if (data === "\u007F") { if (line.current) { line.current = line.current.slice(0, -1); instance.write("\b \b"); } } else if (data === "\u0003") { line.current = ""; instance.write("^C\r\n› "); } else if (data >= " ") { line.current += data; instance.write(data); } }); const resize = () => fit.fit(); window.addEventListener("resize", resize); instance.write("› "); }); return () => { disposed = true; terminal.current?.dispose(); terminal.current = null; }; }, []);
  useEffect(() => { const instance = terminal.current; if (!instance) return; instance.clear(); instance.write("\x1b[H"); if (runtime.transcript.length) instance.writeln(runtime.transcript.join("\r\n\r\n")); instance.write("\r\n› "); }, [runtime.transcript]);
  useEffect(() => { if (runtime.surface.open && !runtime.surface.minimised && runtime.surface.tab === "terminal") { runtime.markRead(); setTimeout(() => terminal.current?.focus(), 60); } }, [runtime.surface.open, runtime.surface.minimised, runtime.surface.tab]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="xterm-host" ref={host} aria-label="MichaelOS Agent CLI"/>;
}

function AiConsole() {
  const runtime = useCapabilities(); const [prompt, setPrompt] = useState("Find the project that best demonstrates platform engineering and open it."); const [trace, setTrace] = useState<{ label: string; call: string; result: string }[]>([]); const [running, setRunning] = useState(false);
  const call = async (label: string, command: string) => { const result = await runCommand(command, { caller: "agent", execute: runtime.execute, history: runtime.history, clear: runtime.clearTranscript }); setTrace(current => [...current, { label, call: command, result }]); return result; };
  const submit = async () => { setTrace([]); setRunning(true); const lower = prompt.toLowerCase(); try { if (lower.includes("project")) { await call("Discovering project capabilities", "capabilities --search project"); await call("Inspecting project.search", "describe project.search"); const query = lower.includes("platform") ? "platform" : prompt; const result = await call("Searching projects", `run project.search --query "${query}"`); const envelope = JSON.parse(result) as { data?: { projects?: { slug: string }[] } }; const match = envelope.data?.projects?.[0]; if (!match) { setTrace(current => [...current, { label: "Finished", call: "No further call", result: "No matching project was returned. Nothing was opened." }]); return; } await call("Opening the strongest returned result", `run project.view --slug ${match.slug}`); } else if (lower.includes("article") || lower.includes("writing")) { await call("Discovering article capabilities", "capabilities --search article"); await call("Searching articles", `run article.search --query "${prompt}"`); } else if (lower.includes("cv")) await call("Opening the CV", "run cv.view"); else setTrace([{ label: "Unable to plan safely", call: "No capability call", result: "I could not map this request to a registered capability. Try asking about projects, articles, or the CV." }]); } finally { setRunning(false); } };
  return <div className="ai-client"><div className="ai-request"><label htmlFor="agent-prompt">Natural-language request</label><textarea id="agent-prompt" value={prompt} onChange={event => setPrompt(event.target.value)}/><button onClick={submit} disabled={running}>{running ? "Working…" : "Run through capabilities"}</button></div><div className="ai-trace">{trace.length === 0 ? <p>The local planner only sees capability metadata and structured results. It never inspects the DOM.</p> : trace.map((step, index) => <article key={`${step.call}-${index}`}><span>{index + 1}</span><div><b>{step.label}</b><code>{step.call}</code><pre>{step.result}</pre></div></article>)}</div></div>;
}

export function ExecutionInspector({ compact = false }: { compact?: boolean }) { const { last } = useCapabilities(); if (!last) return <div className="global-inspector empty">Run a capability from any client to inspect its shared execution event.</div>; return <div className={`global-inspector ${compact ? "compact" : ""}`}><dl><dt>Capability</dt><dd><code>{last.capabilityId}</code></dd><dt>Caller</dt><dd><span className="caller">{last.caller}</span></dd><dt>Status</dt><dd className={last.status}>{last.status}</dd><dt>Parameters</dt><dd><code>{JSON.stringify(last.params)}</code></dd><dt>Duration</dt><dd>{last.durationMs} ms</dd><dt>CLI</dt><dd><code>{last.resolvedCli}</code></dd><dt>Action Keys</dt><dd><code>{last.resolvedActionKeys ?? last.resolvedProtocol ?? "UNRESOLVED"}</code></dd><dt>Accessible name</dt><dd>{last.accessibilityLabel}</dd><dt>Timestamp</dt><dd>{new Date(last.timestamp).toLocaleString()}</dd>{!compact && <><dt>Result</dt><dd><pre>{JSON.stringify(last.result ?? last.error, null, 2)}</pre></dd></>}</dl></div>; }

export function AgentSurface() {
  const runtime = useCapabilities(); const tab = runtime.surface.tab; const select = (next: SurfaceTab) => runtime.execute(next === "terminal" ? "system.openTerminal" : next === "agent" ? "system.openAiConsole" : "system.openInspector").then(() => undefined);
  return <><div className={`protocol-hud ${runtime.protocol.active ? "active" : ""}`} role="status" aria-live="assertive"><b>ACTION KEYS ACTIVE</b><span>{runtime.protocol.buffer || "Enter an Action Key…"}</span><small>Enter to execute · Escape to cancel</small></div>{runtime.toast && <div className={`cap-toast ${runtime.toast.status}`} role="status"><b>{runtime.toast.title}</b>{runtime.toast.detail && <span>{runtime.toast.detail}</span>}</div>}<div className="agent-launcher-wrap"><button className="agent-launcher" data-capability-id="system.openCommandSurface" aria-label="Open agent capability console" onClick={() => runtime.execute("system.openCommandSurface")}>⌘{runtime.unread > 0 && <span>{runtime.unread}</span>}</button><CapabilityInfo capabilityId="system.openCommandSurface" controlLabel="Open agent capability console"/></div>{runtime.surface.open && <section className={`agent-surface ${runtime.surface.minimised ? "minimised" : ""}`} aria-label="MichaelOS capability console"><header><div><i/>MichaelOS Capability Console</div><div className="surface-window-actions"><SurfaceAction id="system.minimiseCommandSurface" label="Minimise agent capability console">_</SurfaceAction><SurfaceAction id="system.closeCommandSurface" label="Close agent capability console">×</SurfaceAction></div></header>{!runtime.surface.minimised && <><nav aria-label="Capability console clients"><button className={tab === "terminal" ? "active" : ""} onClick={() => select("terminal")}>Agent CLI</button><button className={tab === "agent" ? "active" : ""} onClick={() => select("agent")}>Deterministic search</button><button className={tab === "inspector" ? "active" : ""} onClick={() => select("inspector")}>Inspector</button><button onClick={() => runtime.execute("navigation.goCapabilities")}>Full registry ↗</button></nav><div className="surface-content">{tab === "terminal" ? <TerminalClient/> : tab === "agent" ? <AiConsole/> : <ExecutionInspector/>}</div><footer>{runtime.last ? `Last: ${runtime.last.capabilityId} · ${runtime.last.caller} · ${runtime.last.durationMs} ms` : "No capability executed in this browser yet"}</footer></>}</section>}</>;
}
